import type { Language } from "./types";
export const labels: Record<string, [string, string]> = {
  overview: ["Overview", "Aperçu"],
  museum: ["Museum", "Musée"],
  villagers: ["Villagers", "Villageois"],
  encyclopedia: ["Encyclopaedia", "Encyclopédie"],
  settings: ["Settings", "Réglages"],
  fish: ["Fish", "Poissons"],
  bugs: ["Insects", "Insectes"],
  insect: ["Insects", "Insectes"],
  flora: ["Flora", "Flore"],
  archaeology: ["Archaeology", "Archéologie"],
  artifacts: ["Artifacts", "Artefacts"],
  crops: ["Crops", "Cultures"],
  forageables: ["Forageables", "Cueillette"],
  dishes: ["Cooked dishes", "Plats cuisinés"],
  recipes: ["Recipes", "Recettes"],
  furniture: ["Furniture", "Mobilier"],
  materials: ["Materials", "Matériaux"],
  blacksmithing: ["Blacksmithing", "Forge"],
  ranching: ["Ranching", "Élevage"],
  songs: ["Song crystals", "Cristaux musicaux"],
  dating: ["Keepsakes", "Souvenirs"],
  invitations: ["Date invitations", "Invitations"],
  perks: ["Perks", "Compétences"],
  scrolls: ["Spells & scrolls", "Sorts et parchemins"],
  other: ["Other items", "Autres objets"],
  animals: ["Animals", "Animaux"],
  cosmetics: ["Cosmetics", "Apparences"],
  spring: ["Spring", "Printemps"],
  summer: ["Summer", "Été"],
  fall: ["Autumn", "Automne"],
  autumn: ["Autumn", "Automne"],
  winter: ["Winter", "Hiver"],
  river: ["River", "Rivière"],
  pond: ["Pond", "Étang"],
  ocean: ["Ocean", "Océan"],
  mines: ["Mines", "Mines"],
  search: ["Search your journal…", "Rechercher dans votre journal…"],
  filters: ["Filters", "Filtres"],
  sort: ["Sort", "Trier"],
  all: ["All", "Tout"],
  found: ["Discovered", "Découverts"],
  missing: ["Undiscovered", "À découvrir"],
  donated: ["Donated", "Donné au musée"],
  notDonated: ["Not donated yet", "Pas encore donné"],
  season: ["Season", "Saison"],
  place: ["Location", "Lieu"],
  name: ["Name", "Nom"],
  reset: ["Reset filters", "Réinitialiser"],
  yourJourney: ["Your Mistria journey", "Votre aventure à Mistria"],
  welcome: [
    "A little more discovered, every day.",
    "Chaque jour, une nouvelle découverte.",
  ],
  collectionProgress: ["Your collections", "Vos collections"],
  discoveries: ["Items discovered", "Objets découverts"],
  donations: ["Museum donations", "Dons au musée"],
  recipesKnown: ["Recipes learned", "Recettes apprises"],
  villagersMet: ["Villagers met", "Villageois rencontrés"],
  museumHelp: [
    "Every find has a place here.",
    "Chaque découverte a sa place ici.",
  ],
  villagersHelp: [
    "Familiar faces, thoughtful gifts.",
    "Des visages familiers, des cadeaux attentionnés.",
  ],
  encyclopediaHelp: [
    "A place for everything you discover.",
    "Une place pour toutes vos découvertes.",
  ],
  browse: ["Browse collection", "Ouvrir la collection"],
  back: ["All categories", "Toutes les catégories"],
  loved: ["Loved", "Adorés"],
  liked: ["Liked", "Appréciés"],
  unknownVillager: ["Someone to meet", "Une future rencontre"],
  unknownItem: ["Undiscovered", "À découvrir"],
  hiddenHelp: [
    "Keep exploring to reveal this discovery.",
    "Continuez votre exploration pour révéler cette découverte.",
  ],
  hints: ["Gentle hints", "Indices légers"],
  hintTitle: ["A little nudge", "Un petit indice"],
  close: ["Close", "Fermer"],
  details: ["Details", "Détails"],
  sources: ["Also appears in", "Apparaît aussi dans"],
  ingredients: ["Ingredients", "Ingrédients"],
  notes: ["Your notes", "Vos notes"],
  notesHelp: [
    "A place, a plan, something to remember…",
    "Un lieu, une idée, quelque chose à retenir…",
  ],
  save: ["Save note", "Enregistrer"],
  saved: ["Saved locally", "Enregistré localement"],
  noteError: [
    "Could not save your note. Please retry.",
    "Impossible d’enregistrer votre note. Réessayez.",
  ],
  noResults: [
    "No discoveries match this search.",
    "Aucune découverte ne correspond.",
  ],
  noFilterResults: [
    "No entries match these filters.",
    "Aucune entrée ne correspond aux filtres.",
  ],
  results: ["results", "résultats"],
  thisPage: ["In this section", "Dans cette section"],
  journal: ["Elsewhere in your journal", "Ailleurs dans votre journal"],
  allSeasons: ["All seasons", "Toutes les saisons"],
  allPlaces: ["All locations", "Tous les lieux"],
  nameAsc: ["Name · A–Z", "Nom · A–Z"],
  nameDesc: ["Name · Z–A", "Nom · Z–A"],
  foundFirst: ["Discovered first", "Découverts en premier"],
  missingFirst: ["Undiscovered first", "À découvrir en premier"],
  showAll: ["Show everything", "Tout afficher"],
  spoilerFree: ["Spoiler-free", "Sans spoiler"],
  spoilerHelp: [
    "Reveal discoveries at your own pace.",
    "Découvrez Mistria à votre rythme.",
  ],
  showAllHelp: [
    "Reveal the full catalogue. Missing entries stay greyed out.",
    "Révélez tout le catalogue. Les entrées manquantes restent grisées.",
  ],
  hintsHelp: [
    "Click a hidden slot for a small, optional hint.",
    "Cliquez sur une case cachée pour obtenir un indice discret.",
  ],
  language: ["Language", "Langue"],
  appearance: ["Your journal", "Votre journal"],
  preparing: ["Preparing your journal", "Préparation de votre journal"],
  preparingHelp: [
    "Bringing your discoveries and local artwork together.",
    "Rassemblement de vos découvertes et illustrations locales.",
  ],
  tracking: ["Live tracking ready", "Suivi en direct prêt"],
  waiting: ["Waiting for the companion", "En attente du compagnon"],
  offline: ["Tracking unavailable", "Suivi indisponible"],
  local: ["Saved on this computer", "Enregistré sur cet ordinateur"],
  retry: ["Try again", "Réessayer"],
  import: ["Refresh backup discoveries", "Actualiser depuis la copie"],
  importHelp: [
    "Automatically reads your latest approved Desktop backup on startup.",
    "Lit automatiquement votre dernière copie approuvée du Bureau au démarrage.",
  ],
  noData: [
    "Your journal is ready to begin",
    "Votre journal attend votre aventure",
  ],
  noDataHelp: [
    "Load a supported profile and connect the companion to reveal your discoveries.",
    "Chargez un profil compatible et connectez le compagnon pour retrouver vos découvertes.",
  ],
  recorded: ["Recorded in your backup", "Enregistré dans votre copie"],
  fish_caught: ["Fish caught", "Poissons pêchés"],
  bugs_caught: ["Insects caught", "Insectes capturés"],
  crop_harvests: ["Crop harvests", "Récoltes"],
  forageable_harvests: ["Forage finds", "Cueillettes"],
  gifts_given: ["Gifts given", "Cadeaux offerts"],
  items_cooked: ["Dishes cooked", "Plats cuisinés"],
  total: ["total", "au total"],
  of: ["of", "sur"],
  viewMore: ["Show more", "Afficher plus"],
  illustrationMissing: ["Artwork unavailable", "Illustration indisponible"],
  hint_fish: [
    "Watch the water. Different waters hold different surprises.",
    "Observez l’eau. Chaque étendue réserve ses surprises.",
  ],
  hint_fish_cave: [
    "Try casting a line in the caves, where daylight cannot reach.",
    "Essayez de lancer votre ligne dans les grottes, là où la lumière du jour n’entre pas.",
  ],
  hint_fish_coast: [
    "The shoreline may be more promising than inland water.",
    "Le littoral pourrait être plus prometteur que les eaux intérieures.",
  ],
  hint_fish_river: [
    "Follow moving water rather than a still pool.",
    "Suivez l’eau qui coule plutôt qu’une étendue immobile.",
  ],
  hint_fish_pond: [
    "Try a quiet pool away from the current.",
    "Essayez une eau calme, loin du courant.",
  ],
  hint_region_east: [
    "A path toward the east may be worth another look.",
    "Un chemin vers l’est mérite peut-être un autre regard.",
  ],
  hint_crops: [
    "Some discoveries begin with a seed and a little patience.",
    "Certaines découvertes commencent par une graine et un peu de patience.",
  ],
  hint_bugs: [
    "Slow down outdoors. Something small may be moving nearby.",
    "Ralentissez dehors. Quelque chose de petit bouge peut-être tout près.",
  ],
  hint_artifacts: [
    "The past leaves small traces for curious explorers.",
    "Le passé laisse de petites traces aux explorateurs curieux.",
  ],
  hint_recipes: [
    "New ideas can come from people, shops and your own progress.",
    "De nouvelles idées viennent des rencontres, des boutiques et de vos progrès.",
  ],
  hint_gift: [
    "Pay attention to the little things this person enjoys.",
    "Prêtez attention aux petites choses que cette personne apprécie.",
  ],
  hint_generic: [
    "Try a different activity, or revisit a familiar place.",
    "Essayez une autre activité ou revisitez un endroit familier.",
  ],
  scopeNote: [
    "Collection progress · separate from Steam achievements",
    "Progression des collections · distincte des succès Steam",
  ],
  countHelp: [
    "Found items and donations are tracked separately.",
    "Les objets trouvés et les dons sont suivis séparément.",
  ],
};
export const tr = (language: Language, key: string) =>
  labels[key]?.[language === "fra" ? 1 : 0] ?? key.replaceAll("_", " ");
export const categoryOrder = [
  "fish",
  "bugs",
  "crops",
  "forageables",
  "artifacts",
  "dishes",
  "recipes",
  "furniture",
  "blacksmithing",
  "materials",
  "ranching",
  "animals",
  "cosmetics",
  "perks",
  "scrolls",
  "invitations",
  "dating",
  "songs",
  "other",
];
