import type { Entry, Journal } from "./types";
const trout: Entry = {
  key: "e1",
  id: "trout",
  category: "fish",
  name: "Trout",
  description: "A river fish.",
  art: null,
  found: true,
  revealed: true,
  donated: false,
  seasons: ["spring"],
  places: ["river"],
  sources: [],
  ingredients: [],
};
export const testJournal: Journal = {
  entries: [
    trout,
    { ...trout, key: "e2", id: "rainbow_trout", name: "Rainbow Trout" },
    {
      ...trout,
      key: "e3",
      id: null,
      name: null,
      description: null,
      found: false,
      revealed: false,
      hint: { kind: "fish", activity: null, areas: ["mines"], seasons: [], source: null },
      seasons: [],
      places: [],
    },
  ],
  sets: [
    {
      id: "spring_river",
      wing: "fish",
      name: "Spring River Fish",
      items: ["e1"],
      completed: 0,
      total: 1,
    },
  ],
  villagers: [
    {
      key: "n1",
      name: "Celine",
      bio: null,
      art: null,
      met: true,
      revealed: true,
      loved: [],
      liked: [],
    },
    {
      key: "n2",
      name: null,
      bio: null,
      art: null,
      met: false,
      revealed: false,
      loved: [],
      liked: [],
    },
  ],
  categories: [{ id: "fish", completed: 2, total: 3 }],
  profile: { name: "Ari", farm: "Test Farm" },
  stats: {},
};
